### PR TITLE
updates to Linux & MacOS signatures

### PR DESCRIPTION
**Pull request by gsteenss**
updated Linux & MacOS signatures with direct references to sourcecode from the offline installer

### CODE REVIEW

**Comment by 0xPoly** [comment]
Hey, could you make a pull request with only the macos and windows commits?

**Comment by 0xPoly** [comment]
If you're finding it tricky, just tell me and I'll do it.

**Comment by gsteenss** [comment]
let me retry...

**Comment by gsteenss** [comment]
hmmm, no idea how to just include the changes of those files for or revert my linux commits using the github UI. Guess I should start learning plain git commands...

**Comment by 0xPoly** [comment]
The problem is that you submitted a new version of the Windows file, but this pull request is based on code before that. As such, the diff for the windows can't be merge automatically.

To fix this, you'll have to rebase the comment. To do this:

git fetch upstream
git rebase upstream/master

If you're still having trouble, we can skip git alltogather.

**Comment by gsteenss** [comment]
Well... this clearly isn't working out for either for git or me.
Guess it's time to revert to an earlier know good state...

**Pull request closed without merging**
